### ISSUE TITLE
 cascading.flow.planner.PlannerException - pattern-examples-1.0.0-wip-dev.jar

### ISSUE THREAD

**Issue by BramhaAelem** [Cascading/pattern#3]
14/12/21 16:45:02 INFO util.HadoopUtil: resolving application jar from found main method on: cascading.pattern.Main
14/12/21 16:45:02 INFO planner.HadoopPlanner: using application jar: /home/hadoop/my-tmp/cascading/pattern-examples-1.0.0-wip-dev.jar
14/12/21 16:45:02 INFO property.AppProps: using app.id: 1C4CBFB20F6645199E8FADC496C9F505
14/12/21 16:45:04 INFO util.NativeCodeLoader: Loaded the native-hadoop library
14/12/21 16:45:04 WARN snappy.LoadSnappy: Snappy native library not loaded
14/12/21 16:45:04 INFO mapred.FileInputFormat: Total input paths to process : 1
Exception in thread "main" cascading.flow.planner.PlannerException: not all sink taps bound to tail pipes, remaining sink tap names: ['classify']
    at cascading.flow.planner.FlowPlanner.verifyPipeAssemblyEndPoints(FlowPlanner.java:312)
    at cascading.flow.planner.FlowPlanner.verifyAssembly(FlowPlanner.java:166)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:248)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:80)
    at cascading.flow.FlowConnector.connect(FlowConnector.java:459)
    at cascading.pattern.Main.main(Main.java:79)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:160)

**Comment by fs111** [comment]
Hey,

I am currently unable to reproduce that error. Which version of hadoop are you using? Can you share the exact invocation etc. with us? Thanks!
