### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by TomIsYourName** [Cascading/pattern#7]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
    at sun.misc.FDBigInteger.leftShift(FDBigInteger.java:479)
    at sun.misc.FloatingDecimal$ASCIIToBinaryBuffer.doubleValue(FloatingDecimal.java:1319)
    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.lang.Double.parseDouble(Double.java:538)
    at cascading.tuple.coerce.DoubleObjectCoerce.coerce(DoubleObjectCoerce.java:50)
    at cascading.tuple.coerce.DoubleObjectCoerce.coerce(DoubleObjectCoerce.java:29)
    at cascading.tuple.coerce.Coercions.coerce(Coercions.java:208)
    at cascading.pattern.pmml.TreeUtil.getPredicateFor(TreeUtil.java:106)
    at cascading.pattern.pmml.TreeUtil.buildTree(TreeUtil.java:75)
    at cascading.pattern.pmml.TreeUtil.buildTree(TreeUtil.java:77)
    at cascading.pattern.pmml.TreeUtil.buildTree(TreeUtil.java:77)
    at cascading.pattern.pmml.TreeUtil.buildTree(TreeUtil.java:77)
    at cascading.pattern.pmml.TreeUtil.buildTree(TreeUtil.java:77)
    at cascading.pattern.pmml.TreeUtil.buildTree(TreeUtil.java:77)
    at cascading.pattern.pmml.TreeUtil.buildTree(TreeUtil.java:77)
    at cascading.pattern.pmml.TreeUtil.buildTree(TreeUtil.java:77)
    at cascading.pattern.pmml.TreeUtil.createTree(TreeUtil.java:64)
    at cascading.pattern.pmml.PMMLPlanner.handleMiningModel(PMMLPlanner.java:684)
    at cascading.pattern.pmml.PMMLPlanner.resolveAssembly(PMMLPlanner.java:543)
    at cascading.pattern.pmml.PMMLPlanner.resolveTails(PMMLPlanner.java:442)
    at cascading.flow.planner.FlowPlanner.resolveAssemblyPlanners(FlowPlanner.java:158)
    at cascading.flow.planner.FlowPlanner.resolveTails(FlowPlanner.java:145)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:253)
    at cascading.flow.hadoop.planner.HadoopPlanner.buildFlow(HadoopPlanner.java:80)
    at cascading.flow.FlowConnector.connect(FlowConnector.java:459)
    at cascading.pattern.Main.main(Main.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
    at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

I got this when trying to run the example jar with my own model and test data, any advice?

**Comment by cwensel** [comment]
You simply need to increase the memory allocated to your jvm.

**Comment by TomIsYourName** [comment]
Yes, i did, but the issue still remains @cwensel
